openapi: 3.0.0
info:
  version: 0.0.1
  title: Health Data Consent Manager
  description: >
    Entity which provides health information aggregation services to customers of health care services.
    It enables customers to fetch their health information from one or more Health Information Providers
    (e.g., Hospitals, Diagnostic Labs, Medical Device Companies), based on their explicit Consent and to share such
    aggregated information with Health Information Users i.e. entities in need of such data (e.g., Insurers,
    Doctors, Medical Researchers).

servers:
  - url: https://ncg-dev.projecteka.in/consent-manager
    description: Dev

tags:
  - name: consent
  - name: data flow

paths:
  # consent-service
  /consent-requests:
    post:
      tags:
        - consent
      summary: Create consent request
      description: Creates a consent request to get data about a patient by HIU user.
      operationId: createConsentRequest
      parameters:
        - $ref: '#/components/parameters/authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsentRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/ConsentRequest'
      responses:
        '200':
          description: Successful creation of consent request
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
            application/xml:
              schema:
                type: object
                properties:
                  consentRequest:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
        '400':
          description:  >
            **Causes:**
              * Invalid data being sent such as patient doesn't exist in the system.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description:  >
            **Causes:**
              * Expired/Invalid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: >
            **Causes:**
              * Downstream system(s) is down.
              * Unhandled exceptions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /consents/{consent-id}:
    get:
      tags:
        - consent
      summary: Get a specific consent
      description: Fetch a consent artefact associated with the consent-id
      operationId: fetchConsentArtefact
      parameters:
        - $ref: '#/components/parameters/authorization'
        - name: consent-id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: a consent artefact.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsentArtefactRepresentation'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConsentArtefactRepresentation'
        '404':
          description: Consent artefact doesn't exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description:  >
            **Causes:**
              * Expired/Invalid token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: >
            **Causes:**
              * Downstream system(s) is down.
              * Unhandled exceptions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health-information/request:
    post:
      tags:
        - data flow
      summary: Request for health information
      description: The HIU submits the Consent Artefact ID of the consent required for fetching helath information from the HIP(s). A transaction ID is generated and returned.
      parameters:
        - $ref: '#/components/parameters/authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthInformationRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/HealthInformationRequest'
      responses:
        '204':
          description: Accepted.
        '400':
          description: >
            **Causes:**
              * Consent artefact Id is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: >
            **Causes:**
              * Unauthorized HIU
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: >
            **Causes:**
              * Downstream system(s) is down.
              * Unhandled exceptions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /health-information/notification:
    post:
      tags:
        - notification
      description: Notifications corresponding to events during data flow
      parameters:
        - $ref: '#/components/parameters/authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HINotification'
          application/xml:
            schema:
              $ref: '#/components/schemas/HINotification'
      responses:
        '204':
          description: Notification is Accepted
        '400':
          description: >
            **Causes:**
              * Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  parameters:
    authorization:
      name: Authorization
      in: header
      required: true
      description: Bearer token which gateway got after logged in with auth server.
      schema:
        type: string
    limit:
      name: limit
      in: query
      description: How many items to return at one time (max 100) (recommended to sent always)
      required: false
      schema:
        type: integer
        format: int32
    offset:
      name: offset
      in: query
      description: How many items out of line.
      required: false
      schema:
        type: integer
        format: int32
  schemas:
    UuidSchema:
      type: string
      format: uuid
      example: a1s2c932-2f70-3ds3-a3b5-2sfd46b12a18d
    ErrorResponse:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/Error'
      xml:
        name: ErrorResponse
    Error:
      type: object
      properties:
        code:
          type: integer
          enum: [1000, 10001]
          description: >
            1. Error code 1000 : No patient found
            2. Error code 1001: Multiple patients found
        message:
          type: string
      xml:
        name: Error
    Requester:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        identifier:
          $ref: '#/components/schemas/Identifier'
    OrganizationRepresentation:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          xml:
            attribute: true
      xml:
        name: OrganizationResponse
    Organization:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          xml:
            attribute: true
    Identifier:
      type: object
      required:
        - value
      properties:
        value:
          type: string
        type:
          type: string
        system:
          type: string
          format: uri
    HITypeEnum:
      type: string
      enum:
        - Condition
        - Observation
        - MedicationRequest
        - DiagnosticReport
      xml:
        name: HIType
    Permission:
      type: object
      properties:
        accessMode:
          type: string
          enum: [VIEW, STORE, QUERY, STREAM]
        dateRange:
          type: object
          properties:
            from:
              type: string
              format: date-time
            to:
              type: string
              format: date-time
        dataEraseAt:
          type: string
          format: date-time
        frequency:
          type: object
          properties:
            unit:
              type: string
              enum: [HOUR, WEEK, DAY, MONTH, YEAR]
            value:
              type: integer
            repeats:
              type: integer
      xml:
        name: Permission
    ConsentRequest:
      type: object
      required:
        - requestId
        - consent
      properties:
        requestId:
          $ref: '#/components/schemas/UuidSchema'
        consent:
          type: object
          required:
            - purpose
            - patient
            - hiu
            - requester
            - hiTypes
            - permission
            - consentNotificationUrl
          properties:
            purpose:
              $ref: '#/components/schemas/UsePurpose'
            patient:
              type: object
              allOf:
                - $ref: '#/components/schemas/ConsentManagerPatientID'
                - xml:
                    name: patient
            hip:
              type: object
              allOf:
                - $ref: '#/components/schemas/OrganizationRepresentation'
                - xml:
                    name: hip
            hiu:
              type: object
              allOf:
                - $ref: '#/components/schemas/OrganizationRepresentation'
                - xml:
                    name: hiu
            requester:
              $ref: '#/components/schemas/Requester'
            hiTypes:
              type: array
              items:
                $ref: '#/components/schemas/HITypeEnum'
            permission:
              $ref: '#/components/schemas/Permission'
    ConsentManagerPatientID:
      type: object
      properties:
        id:
          type: string
          xml:
            attribute: true
          format: <user-id>@<ncg-id>
          example: batman@ncg
    UsePurpose:
      type: object
      required:
        - text
        - code
      properties:
        text:
          type: string
        code:
          type: string
          description: From the fixed set, documented at refUri
        refUri:
          type: string
          format: uri
    ConsentStatus:
      type: string
      enum:
        - REQUESTED
        - EXPIRED
        - DENIED
        - GRANTED
        - ROVKED
    ConsentArtefactRepresentation:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ConsentStatus'
        consentDetail:
          type: object
          properties:
            schemaVersion:
              type: string
              format: string
            consentId:
              type: string
              format: uuid
            createdAt:
              type: string
              format: date-time
            patient:
              $ref: '#/components/schemas/ConsentManagerPatientID'
            careContexts:
              type: array
              items:
                type: object
                required:
                  - patientReference
                  - careContextReference
                properties:
                  patientReference:
                    type: string
                    example: batman@tmh
                  careContextReference:
                    type: string
                    example: Episode1
            purpose:
              $ref: '#/components/schemas/UsePurpose'
            hip:
              type: object
              allOf:
                - $ref: '#/components/schemas/OrganizationRepresentation'
                - xml:
                    name: hip
            hiu:
              type: object
              allOf:
                - $ref: '#/components/schemas/OrganizationRepresentation'
                - xml:
                    name: hiu
            consentManager:
              type: object
              allOf:
                - $ref: '#/components/schemas/Organization'
                - xml:
                    name: consentManager
            requester:
              $ref: '#/components/schemas/Requester'
            hiTypes:
              type: array
              items:
                $ref: '#/components/schemas/HITypeEnum'
            permission:
              $ref: '#/components/schemas/Permission'
        signature:
          type: string
          example: Signature of CM as defined in W3C standards; Base64 encoded
    HealthInformationRequest:
      type: object
      required:
        - consentArtefactId
        - dataPushUrl
      properties:
        requestId:
          $ref: '#/components/schemas/UuidSchema'
        consent:
          $ref: '#/components/schemas/consent'
        dateRange:
          $ref: '#/components/schemas/dateRange'
        dataPushUrl:
          type: string
          example: 'http://localhost:8003/data/notification'
        keyMaterial:
          $ref: '#/components/schemas/keyMaterial'
    consent:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    dateRange:
      type: object
      required:
        - from
        - to
      properties:
        from:
          type: string
          format: date-time
        to:
          type: string
          format: date-time
    keyMaterial:
      type: object
      required:
        - cryptoAlg
        - curve
        - DHPublicKey
        - nonce
      properties:
        cryptoAlg:
          type: string
          format: string
          example: ECDH
        curve:
          type: string
          format: string
          example: Curve25519
        dhPublicKey:
          $ref: '#/components/schemas/keyObject'
        nonce:
          type: string
          format: 32 byte string
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
    keyObject:
      type: object
      required:
        - expiry
        - parameters
        - keyValue
      properties:
        expiry:
          type: string
          format: date-time
        parameters:
          type: string
          format: string
          example: Curve25519/32byte random key
        keyValue:
          type: string
          format: string
    HINotification:
      type: object
      properties:
        requestId:
          type: string
        consentId:
          type: string
        doneAt:
          type: string
          format: date-time
        notifier:
          type: object
          properties:
            type:
              type: string
              enum: [HIU, HIP]
            id:
              type: string
              example: tmh
        statusNotification:
          type: object
          properties:
            sessionStatus:
              type: string
              enum: [TRANSFERRED, FAILED]
            hipId:
              type: string
              example: max
            statusResponses:
              type: array
              items:
                type: object
                properties:
                  careContextReference:
                    type: string
                  hiStatus:
                    type: string
                    enum: [DELIVERED, OK, ERRORED]
                    example: OK
                  description:
                    type: string